language: elixir
elixir:
  - 1.3.4
otp_release:
  - 18.2
addons:
  - postgresql: '9.5'
env:
  - MIX_ENV=test
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
before_script:
  - mix do ecto.create, ecto.migrate
  - mix run priv/repo/seeds.exs
script:
  - mix test
