web:
  build: .
  ports:
    - "4000:4000"
  command: mix phoenix.server
  environment:
    - MIX_ENV=dev
    - PORT=4000
  volumes:
    - .:/app
  working_dir: /app
  links:
    - db
db:
  image: postgres:9.5
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=db
